import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@radix-ui/themes/styles.css'
import { ConvexClientProvider } from './convexclientprovider'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                {/* eslint-disable-next-line @next/next/no-sync-scripts */}
                <script src="http://localhost:3000"></script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased overscroll-none`}
            >
                <ConvexClientProvider>{children}</ConvexClientProvider>
            </body>
        </html>
    )
}
